repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix]
        types: [python]
        files: ^(src/|tests/)
      - id: ruff-format
        types: [python]
        files: ^(src/|tests/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: no-commit-to-branch
