name: CI

on: [pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      - name: ⚡ Install latests uv version
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: 💾 Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-
      - name: 📦 Install dependencies
        run: uv sync
      - name: 🧹 Run pre-commit hooks
        run: uv run pre-commit run --all-files
      - name: 🧪 Run tests
        run: uv run pytest -m "not slow"
